version: "3"
services:
  # バックエンド(docker FastAPI)
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back/app:/app/
    tty: true
    restart: on-failure
    working_dir: /app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5001

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000 # 本番で動かす際はコメントアウト
    environment:
      # 環境変数
      - CHOKIDAR_USEPOLLING=true # ホットリロードを可能にする
    volumes:
      - ./front/app:/app
      - node_modules:/app/node_modules # ローカルに入れたくない場合はつける
    tty: true
    # restart: on-failure
    working_dir: /app
    command: yarn dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf.d:/etc/nginx/conf.d
      - ./server/log:/var/log/nginx
      - ./front/app/dist:/www/dist
    tty: true
    restart: on-failure
volumes:
  node_modules:
